// Generated by CoffeeScript 1.4.0
// var Scanner, bleScanner, callback;

var Scanner = require("../StopHciConnect/app.js");
var dbtools = require('../tests/dbtools');

var options = process.argv;

//scan foreach
dbtools.selectdb(function (data) {
    var option =
    {
        "name": options[4],
        "mac": options[2], 
        "flag": options[3]
    };
    // Scanner("hci0",option);
    Scanner.blueHcitool(option, function (datas) {
        // console.log("data:"+datas);
    });
});

