// Generated by CoffeeScript 1.4.0
// var Scanner, bleScanner, callback;

var Scanner = require("../StopHciConnect/app.js");
var dbtools = require('../tests/dbtools');

var options = process.argv;


var waiter = 5000;
var wait = function (mils) {
    var now = new Date;
    while (new Date - now <= mils);
};

// dbtools.selectdb(function(data) {

//   var option0=
//   {
//     "name":data[0]['name'],
//     "mac":data[0]['mac'],
//     "RSSI":data[0]['RSSI']
//   };
//   var option1=
//   {
//     "name":data[1]['name'],
//     "mac":data[1]['mac'],
//     "RSSI":data[1]['RSSI']
//   };
//   var option2=
//   {
//     "name":data[2]['name'],
//     "mac":data[2]['mac'],
//     "RSSI":data[2]['RSSI']
//   };
//   var fun1 = function () {
//     var deferred = Scanner.blueHcitool(option0, function (datas) {
//       // console.log("data:"+datas);
//     });
//     deferred.resolve(data + " fun1");
//     return deferred.promise;
//   }
//
//   var fun2 = function () {
//     var deferred = Scanner.blueHcitool(option1, function (datas) {
//       // console.log("data:"+datas);
//     });
//     deferred.resolve(data + " fun2");
//     return deferred.promise;
//   }
//
//   var fun3 = function () {
//     var deferred = Scanner.blueHcitool(option2, function (datas) {
//       // console.log("data:"+datas);
//     });
//     deferred.resolve(data + " fun3");
//     return deferred.promise;
//   }
//
//   function main(datass) {
//     fun1()
//         .then(fun2)
//         .then(fun3)
//         .done(function (datass) {
//           // cb(null, datass);//ok 获得的最终数据为 --->"test fun1 fun2 fun3"
//         }, function (err) {
//           cb(err);//failed
//         });
//   }
// })


//scan foreach
dbtools.selectdb(function (data) {
    // for(var i=0;i<1;i++)
    // {
    var option =
    {
        "name": options[4],
        "mac": options[2], 
        "flag": options[3]

    };

    // Scanner("hci0",option);


    var macAddr = "00:4D:32:06:24:D1";

    // var connectrRecord=
    // {
    //     "mac":macAddr,
    //     "mi":1.5,
    //     "conSuc":0,
    //     "conFai":0,
    //     "disconSuc":0,
    //     "disconFai":0
    // }
    // dbtools.selectCountdb({"mac":macAddr},function (count) {
    //     console.log("count.length:"+count[0]["mac"]+count.length);
    //     if(count.length===1)
    //     {
    //         dbtools.updataCountdb({"mac":macAddr,"set":connectrRecord});
    //     }
    //     else {
    //         dbtools.insertCountdb(connectrRecord);
    //     }
    // });

    Scanner.blueHcitool(option, function (datas) {
        // console.log("data:"+datas);
    });


    // wait(1000);
// Exit after 1s
//     setTimeout(scanner.destroy, 5000);
//   }


    // var files = [];
    // for (var i = 0; i < data.length; ++i) {
    //   var option=
    //   {
    //     "name":data[i]['name'],
    //     "mac":data[i]['mac'],
    //     "RSSI":data[i]['RSSI']
    //   };
    //   files.push(Scanner.blueHcitool(option,function(datas){
    //     console.log("datas"+datas);
    //   }));
    // }
    //
    // Promise.all(files).then(function(result) {
    //   console.log("result"+result);
    // })


});

